-- Generated by Oracle SQL Developer Data Modeler 21.4.1.349.1605
--   at:        2022-12-18 14:11:45 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE dostawca (
    id_dostawcy NUMBER(3) NOT NULL,
    nazwa       VARCHAR2(200) NOT NULL
);

ALTER TABLE dostawca ADD CONSTRAINT dostawca_pk PRIMARY KEY ( id_dostawcy );

CREATE TABLE kategorie (
    nazwa_kategorii VARCHAR2(50) NOT NULL,
    opis            VARCHAR2(1000)
);

ALTER TABLE kategorie ADD CONSTRAINT kategorie_pk PRIMARY KEY ( nazwa_kategorii );

CREATE TABLE klient (
    id_klienta   NUMBER(8) NOT NULL,
    imie         VARCHAR2(40) NOT NULL,
    nazwisko     VARCHAR2(80) NOT NULL,
    numer_tel    VARCHAR2(13) NOT NULL,
    adres        VARCHAR2(200) NOT NULL,
    email        VARCHAR2(100) NOT NULL,
    kod_pocztowy VARCHAR2(6) NOT NULL
);

ALTER TABLE klient ADD CONSTRAINT klient_pk PRIMARY KEY ( id_klienta );

CREATE TABLE koszyk (
    id_koszyka    NUMBER(12) NOT NULL,
    id_transakcji NUMBER(12) NOT NULL
);

CREATE UNIQUE INDEX koszyk__idx ON
    koszyk (
        id_transakcji
    ASC );

ALTER TABLE koszyk ADD CONSTRAINT koszyk_pk PRIMARY KEY ( id_koszyka );

CREATE TABLE opinia (
    id_opinii       NUMBER(6) NOT NULL,
    opinia          VARCHAR2(500) NOT NULL,
    id_produktu     NUMBER(6) NOT NULL,
    nazwa_kategorii VARCHAR2(50) NOT NULL,
    id_producenta   NUMBER(4) NOT NULL
);

ALTER TABLE opinia ADD CONSTRAINT opinia_pk PRIMARY KEY ( id_opinii );

CREATE TABLE pracownik (
    id_prac           NUMBER(5) NOT NULL,
    imie              VARCHAR2(40) NOT NULL,
    nazwisko          VARCHAR2(80) NOT NULL,
    data_zatrudnienia DATE NOT NULL,
    id_sklep          NUMBER(3) NOT NULL
);

ALTER TABLE pracownik ADD CONSTRAINT pracownik_pk PRIMARY KEY ( id_prac );

CREATE TABLE producent (
    id_producenta NUMBER(4) NOT NULL,
    nazwa         VARCHAR2(200) NOT NULL,
    adres         VARCHAR2(200) NOT NULL,
    numer_tel     VARCHAR2(13) NOT NULL
);

ALTER TABLE producent ADD CONSTRAINT producent_pk PRIMARY KEY ( id_producenta );

CREATE TABLE produkt (
    id_produktu     NUMBER(6) NOT NULL,
    nazwa           VARCHAR2(100) NOT NULL,
    cena_jedn       NUMBER(8, 2) NOT NULL,
    opis            VARCHAR2(500),
    id_producenta   NUMBER(4) NOT NULL,
    nazwa_kategorii VARCHAR2(50) NOT NULL,
    specyfikacja    VARCHAR2(500)
);

ALTER TABLE produkt
    ADD CONSTRAINT produkt_pk PRIMARY KEY ( id_produktu,
                                            nazwa_kategorii,
                                            id_producenta );

CREATE TABLE produkt_w_koszyku (
    id_produktu     NUMBER(6) NOT NULL,
    nazwa_kategorii VARCHAR2(50) NOT NULL,
    id_producenta   NUMBER(4) NOT NULL,
    ilosc           NUMBER(4) NOT NULL,
    id_koszyka      NUMBER(12),
    znizka          NUMBER(5, 2) NOT NULL
);

ALTER TABLE produkt_w_koszyku
    ADD CONSTRAINT produkt_w_koszyku_pk PRIMARY KEY ( id_produktu,
                                                      nazwa_kategorii,
                                                      id_producenta );

CREATE TABLE sklep (
    id_sklep     NUMBER(3) NOT NULL,
    adres        VARCHAR2(200) NOT NULL,
    kod_pocztowy VARCHAR2(6) NOT NULL
);

ALTER TABLE sklep ADD CONSTRAINT sklep_pk PRIMARY KEY ( id_sklep );

CREATE TABLE transakcja (
    id_transakcji     NUMBER(12) NOT NULL,
    data_zawarcia     DATE NOT NULL,
    id_prac           NUMBER(5) NOT NULL,
    id_klienta        NUMBER(8) NOT NULL,
    id_dostawcy       NUMBER(3) NOT NULL,
    data_dostawy      DATE NOT NULL,
    czy_faktura       VARCHAR2(1) NOT NULL,
    id_koszyka        NUMBER(12) NOT NULL,
    czy_odbior_wlasny VARCHAR2(1) NOT NULL
);

CREATE UNIQUE INDEX transakcja__idx ON
    transakcja (
        id_koszyka
    ASC );

ALTER TABLE transakcja ADD CONSTRAINT transakcja_pk PRIMARY KEY ( id_transakcji );

ALTER TABLE opinia
    ADD CONSTRAINT opinia_produkt_fk FOREIGN KEY ( id_produktu,
                                                   nazwa_kategorii,
                                                   id_producenta )
        REFERENCES produkt ( id_produktu,
                             nazwa_kategorii,
                             id_producenta )
	ON DELETE CASCADE;

ALTER TABLE pracownik
    ADD CONSTRAINT pracownik_sklep_fk FOREIGN KEY ( id_sklep )
        REFERENCES sklep ( id_sklep )
	ON DELETE CASCADE;

ALTER TABLE produkt
    ADD CONSTRAINT produkt_kategorie_fk FOREIGN KEY ( nazwa_kategorii )
        REFERENCES kategorie ( nazwa_kategorii )
	ON DELETE CASCADE;

ALTER TABLE produkt
    ADD CONSTRAINT produkt_producent_fk FOREIGN KEY ( id_producenta )
        REFERENCES producent ( id_producenta )
	ON DELETE CASCADE;

ALTER TABLE produkt_w_koszyku
    ADD CONSTRAINT produkt_w_koszyku_koszyk_fk FOREIGN KEY ( id_koszyka )
        REFERENCES koszyk ( id_koszyka )
	ON DELETE CASCADE;

ALTER TABLE produkt_w_koszyku
    ADD CONSTRAINT produkt_w_koszyku_produkt_fk FOREIGN KEY ( id_produktu,
                                                              nazwa_kategorii,
                                                              id_producenta )
        REFERENCES produkt ( id_produktu,
                             nazwa_kategorii,
                             id_producenta )
	ON DELETE CASCADE;

ALTER TABLE transakcja
    ADD CONSTRAINT transakcja_dostawca_fk FOREIGN KEY ( id_dostawcy )
        REFERENCES dostawca ( id_dostawcy )
	ON DELETE CASCADE;

ALTER TABLE transakcja
    ADD CONSTRAINT transakcja_klient_fk FOREIGN KEY ( id_klienta )
        REFERENCES klient ( id_klienta )
	ON DELETE CASCADE;

ALTER TABLE transakcja
    ADD CONSTRAINT transakcja_koszyk_fk FOREIGN KEY ( id_koszyka )
        REFERENCES koszyk ( id_koszyka )
	ON DELETE CASCADE;

ALTER TABLE transakcja
    ADD CONSTRAINT transakcja_pracownik_fk FOREIGN KEY ( id_prac )
        REFERENCES pracownik ( id_prac )
	ON DELETE CASCADE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             2
-- ALTER TABLE                             22
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
